all: JamalzadaDeVoshoofd4.o JamalzadaDeVosgobord4.o JamalzadaDeVosstapel4.o JamalzadaDeVosbordvakje4.o
	g++ -Wall -o hetspel JamalzadaDeVosgobord4.o JamalzadaDeVosstapel4.o JamalzadaDeVoshoofd4.o
JamalzadaDeVosgobord4.o: JamalzadaDeVosgobord4.cc JamalzadaDeVosgobord4.h
	g++ -Wall -c JamalzadaDeVosgobord4.cc
JamalzadaDeVosstapel4.o: JamalzadaDeVosstapel4.cc JamalzadaDeVosstapel4.h
	g++ -Wall -c JamalzadaDeVosstapel4.cc	
JamalzadaDeVosbordvakje4.o: JamalzadaDeVosbordvakje4.h
JamalzadaDeVoshoofd4.o: JamalzadaDeVoshoofd4.cc JamalzadaDeVosstapel4.h JamalzadaDeVosgobord4.h JamalzadaDeVosbordvakje4.h
	g++ -Wall -c JamalzadaDeVoshoofd4.cc

